name: vcpkg-setup
runs:
  using: 'composite'
  steps:
    - working-directory: ${{ env.VCPKG_INSTALLATION_ROOT }}
      run: |
        git fetch
        git checkout ${{ env.VCPKG_REVISION }}
      shell: bash

    - working-directory: ${{ env.VCPKG_INSTALLATION_ROOT }}
      run: ./bootstrap-vcpkg.sh -disableMetrics
      shell: bash
