name: manifest-setup
inputs:
  file-pattern:
    required: true
  subdirectory:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate manifest file(s) for 7z archives
      run: |
        mkdir -p openmw-deps/${{ inputs.subdirectory }}
        for file in ${{ inputs.file-pattern }}.7z; do
          filename=$(echo "$file" | sed -r 's/\.7z$/\-manifest.txt/')
          echo "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ env.file }}/${file}" > "openmw-deps/${{ inputs.subdirectory }}/$filename"
          shasum -a 512 "$file" >> "openmw-deps/${{ inputs.subdirectory }}/$filename"
        done
      shell: bash
